backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

# These lines should *not* be indented
media_folder: "public/imageCMS" 
public_folder: "/imageCMS" 

collections:
  - name: "public" # Used in routes, e.g., /admin/collections/blog
    label: "Charles Cantin" # Used in the UI
    folder: "posts" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string", required: false}
      - {label: "Author", name: "author", widget: "string", required: false}
      - {label: "Publish Date", name: "date", widget: "datetime", required: false}
      - {label: "Featured Image", name: "thumbnail", widget: "image", required: false}
      - {label: "Body", name: "body", widget: "markdown", required: false}